parameters:
#    riawa_admin.example.class: RIAWA\AdminBundle\Example

services:
#    riawa_admin.example:
#        class: %riawa_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
